[font]
size = 20.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font"
#family = "EnvyCodeR Nerd Font"
style = "Regular"
