devices:
  samplerate: 96000
  chunksize: 4096
  queuelimit: 4
  silence_threshold: -60
  silence_timeout: 3.0
  target_level: 500
  adjust_period: 10
  enable_rate_adjust: true
  enable_resampling: true
  resampler_type: BalancedAsync
  capture_samplerate: 44100
  stop_on_rate_change: false
  rate_measure_interval: 1.0
  capture:
    type: CoreAudio
    channels: 2
    device: "BlackHole 2ch"
  playback:
    type: CoreAudio
    channels: 2
    device: "D50s "
filters:
  hd800_band_1:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 34
      gain: 4
      q: 0.7
  hd800_band_2:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 100
      gain: 4.5
      q: 0.7
  hd800_band_3:
    type: Biquad
    parameters:
      type: Peaking
      freq: 220
      gain: -2.2
      q: 0.9
  hd800_band_4:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1050
      gain: -0.6
      q: 1.0
  hd800_band_5:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1500
      gain: 0.7
      q: 3.0
  hd800_band_6:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2200
      gain: 4.5
      q: 1.2
  hd800_band_7:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2600
      gain: -2.5
      q: 2.5
  hd800_band_8:
    type: Biquad
    parameters:
      type: Peaking
      freq: 5800
      gain: -7.7
      q: 3.5
  hd800_band_9:
    type: Biquad
    parameters:
      type: Peaking
      freq: 7900
      gain: -3.0
      q: 6.0
  hd800_band_10:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 9000
      gain: -3.0
      q: 0.71
mixers:
  hd800_mixer:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      sources:
      - channel: 0
        gain: -8.5
        inverted: false
    - dest: 1
      sources:
      - channel: 1
        gain: -8.5
        inverted: false
pipeline:
  - type: Mixer
    name: hd800_mixer
  - type: Filter
    channel: 0
    names:
    - hd800_band_1
    - hd800_band_2
    - hd800_band_3
    - hd800_band_4
    - hd800_band_5
    - hd800_band_6
    - hd800_band_7
    - hd800_band_8
    - hd800_band_9
    - hd800_band_10
  - type: Filter
    channel: 1
    names:
    - hd800_band_1
    - hd800_band_2
    - hd800_band_3
    - hd800_band_4
    - hd800_band_5
    - hd800_band_6
    - hd800_band_7
    - hd800_band_8
    - hd800_band_9
    - hd800_band_10
