[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[[block]]
block = "temperature"

[[block]]
block = "cpu"
interval = 0.5

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R') "
