apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  selector:
    matchLabels:
      app: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - image: ashwinath/ubuntu
        command: ["sleep"]
        args: ["infinity"]
        name: ubuntu
        ports:
        - containerPort: 443
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  ports:
  - port: 443
  selector:
    app: dev
  clusterIP: None
