export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
export GOPATH=$HOME/go

alias vim="nvim"
alias tmux="tmux -u"
alias k="kubectl"
alias g="git"
alias tf="terraform"
alias "c=xclip"
alias "v=xclip -o"

export EDITOR="/usr/bin/nvim"

export TERM=alacritty

alias lsd='ls'
alias du='dust'
alias df='duf'
source <(kubectl completion zsh)

. $HOME/z.sh

function fixssh {
    if [ "$SSH_AUTH_SOCK" != "$HOME/.ssh/ssh_auth_sock" ]; then
        ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
    fi
}

eval `ssh-agent` > /dev/null
fixssh

source $HOME/.passwords
source "$HOME/.cargo/env"
. $HOME/z.sh


function addkeys {
    ssh-add ~/.ssh/id_rsa
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export ZSH_THEME="steeef"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# vpn examples
# sudo wg-quick up sg-sng
# sudo wg-quick up jp-tok
# sudo wg-quick down sg-sng
# sudo wg-quick down jp-tok
